#!/bin/bash
# Script que simplifica a execução do programa.
# O nome é uma homenagem ao "cat" do Pokémon (piadinha ruim).

# Nome dos diretórios
EXDIR="pokemon"
SRCDIR="src"

# --------------------------------------------------------------------
# Mostra como usar o script.

function uso {
    echo -e "\e[1mUSO\e[0m"
    echo -e "\t$1 [\e[1m-i\e[0m] [\e[1m-h\e[0m] <\e[1mPokémon 1\e[0m> <\e[1mPokémon 2\e[0m>\n"

    echo -e "\e[1mDESCRIÇÃO\e[0m"
    echo -e "\tExecuta o src/main.py com os Pokémons citados como parâmetros.\n"

    echo -e "\e[1mOPÇÕES\e[0m"
    echo -e "\tSepare várias opções simultâneas com um espaço.\n"

    echo -e "\t\e[1m-h\e[0m\tMostra como usar o script, além de abandoná-lo.\n"
    echo -e "\t\e[1m-i\e[0m\tMostra os Pokémons disponíveis e abandona o script.\n"

    exit
}

# --------------------------------------------------------------------
# MAIN

for arg in "$@"; do
    case $arg in
    -h)
        uso "$0";;
    -i)
        ls --color=auto $EXDIR
        exit;;
    esac
done

if [ -f "$EXDIR/$1.txt" ]; then
    if [ -f "$EXDIR/$2.txt" ]; then
        cat "$EXDIR/$1.txt" "$EXDIR/$2.txt" - | ./$SRCDIR/main.py
    else
        echo "$2.txt não encontrado!"
    fi
else
    echo "$1.txt não encontrado"
fi
