#!/bin/bash
# Script que acrescenta um virtualenv em um diretório já existente.

# Diretório do projeto
DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

# Arquivo com as dependências
REQ="$DIR/doc/requirements.txt"

# --------------------------------------------------------------------
# Mostra como usar o script.

function uso {
    echo -e "\e[1mUSO\e[0m"
    echo -e "\t./`basename $0` [\e[1m-h\e[0m]\n"

    echo -e "\e[1mDESCRIÇÃO\e[0m"
    echo -e "\tCria um virtualenv para Python 3 no diretório atual."
    echo -e "\tTambém instala as dependências encontradas em '$REQ'.\n"

    echo -e "\e[1mOPÇÕES\e[0m"
    echo -e "\t\e[1m-h\e[0m\tMostra como usar o script, além de abandoná-lo.\n"

    exit
}

# --------------------------------------------------------------------
# MAIN 

# Argumentos por linha de comando
for arg in "$@"; do
    if [ "$arg" == "-h" ]; then uso; fi
done

virtualenv -p python3 $DIR
if [ -f "$REQ" ]; then
    source $DIR/bin/activate
    echo "Installing requirements from $REQ..."
    pip3 install -r $REQ
fi

echo "Done!"
