#!/bin/bash
# Script que acrescenta um virtualenv em um diretório já existente.

# Diretório do projeto
DIR=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

# Arquivo com as dependências
REQ="$DIR/doc/requirements.txt"

# --------------------------------------------------------------------
# Mostra como usar o script.

function uso {
    echo -e "\e[1mUSO\e[0m"
    echo -e "\t./`basename $0` [\e[1m-h\e[0m] [\e[1m-r\e[0m]\n"

    echo -e "\e[1mDESCRIÇÃO\e[0m"
    echo -e "\tCria um virtualenv para Python 3 no diretório atual."
    echo -e "\tTambém instala as dependências encontradas em '$REQ'.\n"

    echo -e "\e[1mOPÇÕES\e[0m"
    echo -e "\tSepare cada opção com um espaço.\n"
    echo -e "\t\e[1m-h\e[0m\tMostra como usar o script, além de abandoná-lo.\n"
    echo -e "\t\e[1m-r\e[0m\tRemove os diretórios instalados por este script, além de abandoná-lo.\n"

    exit
}

# --------------------------------------------------------------------
# MAIN 

# Argumentos por linha de comando
for arg in "$@"; do
    if [ "$arg" == "-h" ]; then uso; fi
    if [ "$arg" == "-r" ]; then
        rm -rf bin include lib
        echo "Diretórios instalados pelo pyenv foram removidos com sucesso!"
        exit 0
    fi
done

virtualenv -p python3 $DIR
if [ -f "$REQ" ]; then
    source $DIR/bin/activate
    echo "Instalando requisitos contidos em $REQ..."
    pip3 install -r $REQ
fi

echo "Pronto! :)"
