#!/bin/bash
# Script que cria um tar.gz do projeto com os arquivos essenciais.
# O nome é uma homenagem a um Pokémon chamado Tyranitar (a zueira não tem fim).

# Nome do diretório local
cd "$(dirname "${BASH_SOURCE[0]}")"
nome=$(basename "$(pwd)")

# Arquivos que não serão copiados para o tar.gz
except="(bin)|(include)|(lib)|(tyranitar)|($nome)"

# --------------------------------------------------------------------
# Mostra como usar o script.

function uso {
    echo -e "\e[1mUSO\e[0m"
    echo -e "\t$0 [\e[1m-h\e[0m]\n"

    echo -e "\e[1mDESCRIÇÃO\e[0m"
    echo -e "\tCria um tar.gz do projeto com os arquivos essenciais."

    echo -e "\e[1mOPÇÕES\e[0m"
    echo -e "\t\e[1m-h\e[0m\tMostra como usar o script, além de abandoná-lo.\n"
    echo -e "\t\e[1m-r\e[0m\tRemove arquivos .tar.gz contidos no diretório.\n"

    exit 0
}

# --------------------------------------------------------------------
# MAIN 

# Argumentos por linha de comando
for arg in "$@"; do
    case $arg in
    -h)
        uso;;
    -r)
        rm -f *".tar.gz"
        exit;;
    esac
done

# Cria o tar.gz
echo "Criando o tar.gz..."

mkdir $nome && cp -rf $(ls | egrep -v "$except") $nome
rm -rf $(find $nome -type d -name __pycache__)
tar -czf $nome.tar.gz $nome
rm -rf $nome

echo -e "Arquivo\033[1;31m $nome.tar.gz \033[0mcriado com sucesso!"
